dsn: ${DSN}

serve:
  public:
    port: 4444
  admin:
    port: 4445

log:
  level: debug

urls:
  self:
    issuer: https://oidc.${DOMAIN}/
  consent: https://idp.${DOMAIN}/consent
  login: https://idp.${DOMAIN}/login
