dsn: ${DSN}

serve:
  public:
    port: 4444
  admin:
    port: 4445
  cookies:
    same_site_mode: Lax

secrets:
  system:
    - 'Yk8m5Zp3Jtq6Lx9rGvF2E4sQwXyH7aN0'

log:
  level: debug

urls:
  self:
    issuer: https://oidc.${DOMAIN}/
  consent: https://id.${DOMAIN}/consent
  login: https://id.${DOMAIN}/api/authenticate
